In [36]:
class Solution:
    def trimMean(self, arr) -> float:
        import numpy as np
        arr = sorted(arr)
        print(arr)
        lena = len(arr)
        print(lena)
        start = np.floor(lena*0.05)
        end = np.ceil(lena*0.95-1)
        print(end, start)
        return sum(arr[start:end+1])/(end-start)

In [38]:
class Solution:
    def trimMean(self, arr) -> float:
        arr = sorted(arr)
        print(arr)
        lena = len(arr)
        multiple = lena/20
        start = int(multiple)
        end = int(lena - 1 - multiple)
        print(end, start)
        return float(sum(arr[start:end+1])/(18*multiple))

In [39]:
if __name__ == '__main__':
    arr = [6,0,7,0,7,5,7,8,3,4,0,7,8,1,6,8,1,1,2,4,8,1,9,5,4,3,8,5,10,8,6,6,1,0,6,10,8,2,3,4]
    solution = Solution()
    print(solution.trimMean(arr))

[0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 9, 10, 10]
37 2
4.777777777777778


NameError: name 'end' is not defined

In [23]:
20*0.95-1

18.0

In [140]:
class Solution:
    def bestCoordinate(self, towers, radius):
        import numpy as np
        #import math
        towers1 = np.array(towers)
        max_x = towers1[:,0].max()
        max_y = towers1[:,1].max()
        matrix = np.array([[0]*(max_y+1)]*(max_x+1))
        for x, y, z in towers:
            for i in range(max_x+1):
                for j in range(max_y+1):
                    #d = math.dist([x,y],[i,j])
                    d = ((x-i)**2+(y-j)**2)**(0.5)
                    if d <= radius:
                        #d = ((x-i)**2+(y-j)**2)**(0.5)
                        matrix[i][j] += int(z/(1+d))
                        print(matrix[17,22], matrix[4, 50], x,y)
        print(matrix, np.max(matrix), np.where(matrix==np.max(matrix)))
                        
        position = np.where(matrix==np.max(matrix))
        print(position)
        return list([int(position[0][0]), int(position[1][0])])
            
        

In [141]:
if __name__ == '__main__':
    solution = Solution()
    towers = [[32,36,27],[17,22,43],[8,11,41],[46,28,7],[22,4,35],[41,8,33],[32,29,4],[44,32,16],[33,20,16],[3,38,35],[17,47,23],[33,0,29],[29,19,6],[4,50,46],[19,47,6],[48,6,41],[20,26,35]]
    radius = 4
    print(solution.bestCoordinate(towers, radius))

0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 32 36
0 0 17 22
0 0 17 22
0 0 17 22
0 0 17 22
0 0 17 22
0 0 17 22
0 0 17 22
0 0 17 22
0 0 17 22
0 0 17 22
0 0 17 22
0 0 17 22
0 0 17 22
0 0 17 22
0 0 17 22
0 0 17 22
0 0 17 22
0 0 17 22
0 0 17 22
0 0 17 22
0 0 17 22
0 0 17 22
0 0 17 22
0 0 17 22
43 0 17 22
43 0 17 22
43 0 17 22
43 0 17 22
43 0 17 22
43 0 17 22
43 0 17 22
43 0 17 22
43 0 17 22
43 0 17 22
43 0 17 22
43 0 17 22
43 0 17 22
43 0 17 22
43 0 17 22
43 0 17 22
43 0 17 22
43 0 17 22
43 0 17 22
43 0 17 22
43 0 17 22
43 0 17 22
43 0 17 22
43 0 17 22
43 0 1

In [75]:
towers = [[1,2,5],[2,1,7],[3,1,9]]
import numpy as np
towers = np.array(towers)
a = np.where(towers == np.max(towers))
int(a[0])

2

In [139]:
import math
math.dist([1,1],[2,1])

AttributeError: module 'math' has no attribute 'dist'

In [58]:
print(matrix)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [69]:
towers = [[1,2,5],[2,1,7],[3,1,9]]
for x, y, z in towers:
    print(x,y)

1 2
2 1
3 1


In [68]:
towers = np.array(towers)

In [ ]:
You are given an array of network towers towers and an integer radius, where towers[i] = [xi, yi, qi] denotes the ith network tower with location (xi, yi) and quality factor qi. All the coordinates are integral coordinates on the X-Y plane, and the distance between two coordinates is the Euclidean distance.

The integer radius denotes the maximum distance in which the tower is reachable. The tower is reachable if the distance is less than or equal to radius. Outside that distance, the signal becomes garbled, and the tower is not reachable.

The signal quality of the ith tower at a coordinate (x, y) is calculated with the formula ⌊qi / (1 + d)⌋, where d is the distance between the tower and the coordinate. The network quality at a coordinate is the sum of the signal qualities from all the reachable towers.

Return the integral coordinate where the network quality is maximum. If there are multiple coordinates with the same network quality, return the lexicographically minimum coordinate.

Note:

A coordinate (x1, y1) is lexicographically smaller than (x2, y2) if either x1 < x2 or x1 == x2 and y1 < y2.
⌊val⌋ is the greatest integer less than or equal to val (the floor function).

In [ ]:
Output: [2,1]
Explanation: 
At coordinate (2, 1) the total quality is 13
- Quality of 7 from (2, 1) results in ⌊7 / (1 + sqrt(0)⌋ = ⌊7⌋ = 7
- Quality of 5 from (1, 2) results in ⌊5 / (1 + sqrt(2)⌋ = ⌊2.07⌋ = 2
- Quality of 9 from (3, 1) results in ⌊9 / (1 + sqrt(1)⌋ = ⌊4.5⌋ = 4
No other coordinate has higher quality.
